

INSERT OR REPLACE INTO IconTextureAtlases 
            (Name,                         				IconSize,   Filename,                             IconsPerRow,	    IconsPerColumn)
VALUES  	('ICON_ATLAS_ACOIAF_GOVERNORS',        		32,        'ICON_GOVERNORS_ACOIAF_32',            8,                1),
			('ICON_ATLAS_ACOIAF_GOVERNORS',             64,        'ICON_GOVERNORS_ACOIAF_64',            8,                1),
			('ICON_ATLAS_ACOIAF_GOVERNORS_FILL',        32,        'ICON_GOVERNORS_ACOIAF_32',            8,                2),
			('ICON_ATLAS_ACOIAF_GOVERNORS_SLOT',        32,        'ICON_GOVERNORS_ACOIAF_32',            8,                2),
			('ICON_ATLAS_ACOIAF_GOVERNORS_FILL',        22,        'ICON_GOVERNORS_ACOIAF_22',            8,                2),
			('ICON_ATLAS_ACOIAF_GOVERNORS_SLOT',        22,        'ICON_GOVERNORS_ACOIAF_22',            8,                2);
			('ICON_ATLAS_ACOIAF_GOVERNOR_PROMOTIONS',   24,        'ICON_GOVERNORS_ACOIAF_24',            8,                2);

INSERT OR REPLACE INTO IconDefinitions 
            (Name,													Atlas,						  			'Index')
VALUES     	('ICON_GOVERNOR_THE_DEFENDER',							'ICON_ATLAS_ACOIAF_GOVERNORS',				0),
			('ICON_GOVERNOR_THE_DEFENDER_FILL',						'ICON_ATLAS_ACOIAF_GOVERNORS_FILL',			0),
			('ICON_GOVERNOR_THE_DEFENDER_SLOT',						'ICON_ATLAS_ACOIAF_GOVERNORS_SLOT',			8),
			('ICON_GOVERNOR_THE_AMBASSADOR',						'ICON_ATLAS_ACOIAF_GOVERNORS',				1),
			('ICON_GOVERNOR_THE_AMBASSADOR_FILL',					'ICON_ATLAS_ACOIAF_GOVERNORS_FILL',			1),
			('ICON_GOVERNOR_THE_AMBASSADOR_SLOT',					'ICON_ATLAS_ACOIAF_GOVERNORS_SLOT',			9),
			('ICON_GOVERNOR_THE_CARDINAL',							'ICON_ATLAS_ACOIAF_GOVERNORS',				2),
			('ICON_GOVERNOR_THE_CARDINAL_FILL',						'ICON_ATLAS_ACOIAF_GOVERNORS_FILL',			2),
			('ICON_GOVERNOR_THE_CARDINAL_SLOT',						'ICON_ATLAS_ACOIAF_GOVERNORS_SLOT',			10),
			('ICON_GOVERNOR_THE_RESOURCE_MANAGER',					'ICON_ATLAS_ACOIAF_GOVERNORS',				3),
			('ICON_GOVERNOR_THE_RESOURCE_MANAGER_FILL',				'ICON_ATLAS_ACOIAF_GOVERNORS_FILL',			3),
			('ICON_GOVERNOR_THE_RESOURCE_MANAGER_SLOT',				'ICON_ATLAS_ACOIAF_GOVERNORS_SLOT',			11),
			('ICON_GOVERNOR_THE_BUILDER',							'ICON_ATLAS_ACOIAF_GOVERNORS',				4),
			('ICON_GOVERNOR_THE_BUILDER_FILL',						'ICON_ATLAS_ACOIAF_GOVERNORS_FILL',			4),
			('ICON_GOVERNOR_THE_BUILDER_SLOT',						'ICON_ATLAS_ACOIAF_GOVERNORS_SLOT',			12),
			('ICON_GOVERNOR_THE_EDUCATOR',							'ICON_ATLAS_ACOIAF_GOVERNORS',				5),
			('ICON_GOVERNOR_THE_EDUCATOR_FILL',						'ICON_ATLAS_ACOIAF_GOVERNORS_FILL',			5),
			('ICON_GOVERNOR_THE_EDUCATOR_SLOT',						'ICON_ATLAS_ACOIAF_GOVERNORS_SLOT',			13),
			('ICON_GOVERNOR_THE_MERCHANT',							'ICON_ATLAS_ACOIAF_GOVERNORS',				6),
			('ICON_GOVERNOR_THE_MERCHANT_FILL',						'ICON_ATLAS_ACOIAF_GOVERNORS_FILL',			6),
			('ICON_GOVERNOR_THE_MERCHANT_SLOT',						'ICON_ATLAS_ACOIAF_GOVERNORS_SLOT',			14),
			('ICON_GOVERNOR_OTHER_AMBASSADORS_FILL',				'ICON_ATLAS_ACOIAF_GOVERNORS_FILL',			8),
			('ICON_GOVERNOR_THE_DEFENDER_PROMOTION',				'ICON_ATLAS_ACOIAF_GOVERNOR_PROMOTIONS',	0),
			('ICON_GOVERNOR_THE_AMBASSADOR_PROMOTION',				'ICON_ATLAS_ACOIAF_GOVERNOR_PROMOTIONS',	1),
			('ICON_GOVERNOR_THE_CARDINAL_PROMOTION',				'ICON_ATLAS_ACOIAF_GOVERNOR_PROMOTIONS',	2),
			('ICON_GOVERNOR_THE_RESOURCE_MANAGER_PROMOTION',		'ICON_ATLAS_ACOIAF_GOVERNOR_PROMOTIONS',	3),
			('ICON_GOVERNOR_THE_BUILDER_PROMOTION',					'ICON_ATLAS_ACOIAF_GOVERNOR_PROMOTIONS',	4),
			('ICON_GOVERNOR_THE_EDUCATOR_PROMOTION',				'ICON_ATLAS_ACOIAF_GOVERNOR_PROMOTIONS',	5),
			('ICON_GOVERNOR_THE_MERCHANT_PROMOTION',				'ICON_ATLAS_ACOIAF_GOVERNOR_PROMOTIONS',	6);
			
